scheduler:
  workersNum: 100
  bucketsNum: 5
  tryLockSeconds: 70
  tryLockGapMilliSeconds: 100
  successExpireSeconds: 130
trigger:
  zrangeGapSeconds: 20
  workersNum: 10000
webserver:
  port: 8888
migrator:
  workersNum: 1000
  migrateStepMinutes: 60
  migrateTryLockMinutes: 20
  migrateSuccessExpireMinutes: 120
  timerDetailCacheMinutes: 2
mysql:
  ### 必填
  dsn: "root:dhxdl666@tcp(47.102.119.88:3306)/timer?charset=utf8mb4&parseTime=True&loc=Local"
  maxOpenConns: 100
  maxIdleConns: 50
pool:
   size: 500000
   expireSeconds: 30
   nonBlocking: false

redis:
  network: tcp
  ## 必填
  address: "47.102.119.88:16379"
  password: "dhxdl666"
  maxIdle: 2000
  idleTimeout: 10
  maxActive: 5000
  wait: true
